server:
  port: 8082

spring:
  application:
    name: query-api
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 5s
          socket-timeout: 30s

app:
  search:
    default-page-size: 20
    max-page-size: 1000
    default-time-range-hours: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.sahanurmondal.loganalytics: DEBUG
    org.springframework.data.elasticsearch: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
